/* ============================================================================
   Penn Judaica Portal — BETA
   data.js — the "harvested index"
   ----------------------------------------------------------------------------
   In production this file would be GENERATED by a server-side harvester that
   ingests Penn's source systems (OPenn / OAI-PMH, IIIF Presentation manifests,
   the Franklin catalog via MARC, Colenda via MODS, and EAD finding aids) into
   one index. See HARVESTING.md. For this beta it is hand-assembled from REAL,
   openly licensed records on Penn's OPenn (https://openn.library.upenn.edu).
   Images load live from OPenn; metadata is baked in so the app works offline.

   Item schema:
     id, title, creator, year, dateText, place, region, lat, lng,
     lang, type, collection, source(key), callno, img (card thumb),
     srcUrl, desc, pages[] -> { img (web), thumb, label }
   ============================================================================ */
(function () {
  var OP = "https://openn.library.upenn.edu";

  var sources = {
    zucker: { label: "Zucker Ketubah Collection", system: "OPenn", color: "#a8492b" },
    ljs:    { label: "Schoenberg Manuscripts",    system: "OPenn", color: "#6e7637" },
    mikveh: { label: "Mikveh Israel Records",     system: "OPenn", color: "#6a4a7c" }
  };

  // build one OPenn page object (web image + thumbnail + label)
  function pg(coll, obj, prefix, idx, label) {
    return {
      img:   OP + "/Data/" + coll + "/" + obj + "/data/web/"   + prefix + "_" + idx + "_web.jpg",
      thumb: OP + "/Data/" + coll + "/" + obj + "/data/thumb/" + prefix + "_" + idx + "_thumb.jpg",
      label: label
    };
  }

  // Zucker ketubah: single sheet (fol. 1r), optionally a verso
  function ket(id, num, prefix, year, dateText, place, region, lat, lng, desc, lang, hasVerso) {
    var obj = "ket_z_" + num;
    var pages = [pg("0051", obj, prefix, "0000", "fol. 1r")];
    if (hasVerso) pages.push(pg("0051", obj, prefix, "0001", "fol. 1v"));
    return {
      id: id,
      title: "Ketubah — " + place.split(",")[0] + ", " + year,
      creator: "Scribe unknown",
      year: year, dateText: dateText, place: place, region: region, lat: lat, lng: lng,
      lang: lang || "Hebrew & Aramaic", type: "Ketubah",
      collection: "Benjamin Zucker Family Ketubah Collection", source: "zucker", iiif: true,
      img: pages[0].img, srcUrl: OP + "/Data/0051/html/" + obj + ".html",
      callno: "KET Z" + parseInt(num, 10), desc: desc, pages: pages
    };
  }

  // Schoenberg LJS 204 — a multi-leaf codex (curated sequence of leaves)
  var ljs204Pages = [
    pg("0001", "ljs204", "0015", "0016", "fol. 1r"),
    pg("0001", "ljs204", "0015", "0017", "fol. 1v"),
    pg("0001", "ljs204", "0015", "0018", "fol. 2r"),
    pg("0001", "ljs204", "0015", "0019", "fol. 2v"),
    pg("0001", "ljs204", "0015", "0020", "fol. 3r"),
    pg("0001", "ljs204", "0015", "0025", "fol. 5v"),
    pg("0001", "ljs204", "0015", "0027", "fol. 6v (table)"),
    pg("0001", "ljs204", "0015", "0028", "fol. 7r (table)"),
    pg("0001", "ljs204", "0015", "0030", "fol. 8r (table)"),
    pg("0001", "ljs204", "0015", "0044", "fol. 15r (table)"),
    pg("0001", "ljs204", "0015", "0000", "Front cover"),
    pg("0001", "ljs204", "0015", "0085", "Back cover")
  ];

  // Haym Salomon manuscript — cover + 8 pages
  var haym = "MikvehIsrael.HaymSalomonManuscript";
  var haymPages = [
    pg("0039", haym, "9537", "0001", "p. 1"),
    pg("0039", haym, "9537", "0002", "p. 2"),
    pg("0039", haym, "9537", "0003", "p. 3"),
    pg("0039", haym, "9537", "0004", "p. 4"),
    pg("0039", haym, "9537", "0005", "p. 5"),
    pg("0039", haym, "9537", "0006", "p. 6"),
    pg("0039", haym, "9537", "0007", "p. 7"),
    pg("0039", haym, "9537", "0008", "p. 8"),
    pg("0039", haym, "9537", "0000", "Cover sheet")
  ];

  // Jonas Phillips letter — 3 pages
  var jonas = "MikvehIsrael.JonasPhillipsLetter1782";
  var jonasPages = [
    pg("0039", jonas, "12146", "0000", "p. 1"),
    pg("0039", jonas, "12146", "0001", "p. 2"),
    pg("0039", jonas, "12146", "0002", "p. 3")
  ];

  var items = [
    {
      id: 1,
      title: "Shesh kenafayim (Six Wings) — astronomical tables",
      creator: "Immanuel ben Jacob Bonfils; scribe Joseph ben Isaac Gallico",
      year: 1509, dateText: "Italy, 1509", place: "Italy", region: "Italy", lat: 43.4, lng: 12.0,
      lang: "Hebrew", type: "Manuscript", collection: "Lawrence J. Schoenberg Collection",
      source: "ljs", iiif: true,
      img: ljs204Pages[0].img, srcUrl: OP + "/Data/0001/html/ljs204.html", callno: "LJS 204",
      desc: "Immanuel Bonfils's set of astronomical tables, the 'Six Wings,' copied in Italy in 1509 by the scribe Joseph ben Isaac Gallico. The tables calculate the movements of the sun and moon and the timing of eclipses for the Jewish calendar. Once owned by the great collector David Solomon Sassoon.",
      pages: ljs204Pages
    },

    ket(2, "071", "10504", 1600, "Modena, Italy · 1600", "Modena, Italy", "Italy", 44.647, 10.925,
      "The earliest ketubah in the Zucker collection, signed in Modena on 8 December 1600 — a Hebrew and Aramaic marriage contract of the Italian Jewish community, formerly in the Sassoon Library of London."),
    ket(3, "007", "10638", 1657, "Izmir, Turkey · 1657", "Izmir, Turkey", "Turkey / Ottoman", 38.423, 27.143,
      "A fragmentary illustrated ketubah from Izmir, 1657 — one of the oldest in the collection. The lower text and decorative borders were later cropped and the couple's names effaced.", null, true),
    ket(4, "113", "10653", 1672, "Florence, Italy · 1672", "Florence, Italy", "Italy", 43.769, 11.256,
      "An Italian ketubah from Florence, 1672, its Aramaic marriage text framed by the decorative borders characteristic of Tuscan Jewish scribal art."),
    ket(5, "111", "10421", 1699, "Cittadella, Italy · 1699", "Cittadella, Italy", "Italy", 45.648, 11.784,
      "An illustrated ketubah from Cittadella in the Veneto, 1699."),
    ket(6, "108", "10435", 1709, "Alessandria, Italy · 1709", "Alessandria, Italy", "Italy", 44.913, 8.615,
      "An illustrated ketubah from Alessandria in Piedmont, 1709.", "Aramaic"),
    ket(7, "020", "10531", 1790, "Meshed, Iran · 1790", "Meshed, Iran", "Iran", 36.297, 59.606,
      "An illustrated ketubah from Meshed (Mashhad), Iran, 1790 — from a community that would later be forced into outward conversion while secretly maintaining Jewish life."),
    ket(8, "081", "10526", 1841, "Egypt · 1841 (Karaite)", "Egypt", "Egypt", 30.044, 31.236,
      "A Karaite ketubah from Egypt, 1841 — a marriage contract following the distinct legal tradition of the Karaite Jews, who reject rabbinic Talmudic law."),
    ket(9, "054", "10474", 1849, "Cochin, India · 1849", "Cochin, India", "India", 9.931, 76.267,
      "An illustrated ketubah from the ancient Jewish community of Cochin on the Malabar Coast of India, 1849."),
    ket(10, "001", "10411", 1878, "Amadiyah, Iraq · 1878", "Amadiyah, Iraq", "Iraq / Kurdistan", 37.092, 43.487,
      "An illustrated ketubah from the Kurdish Jewish community of Amadiya (Amadiyah), in the mountains of northern Iraq, 1878."),
    ket(11, "110", "10596", 1879, "Bologna, Italy · 1879", "Bologna, Italy", "Italy", 44.494, 11.343,
      "An illustrated ketubah from Bologna, Italy, 1879."),
    ket(12, "041", "10571", 1881, "Bombay, India · 1881", "Bombay, India", "India", 19.076, 72.878,
      "A large illustrated ketubah from Bombay, 1881, from the Baghdadi Jewish community of western India; formerly in the Sassoon Library."),
    ket(13, "096", "10441", 1889, "Herat, Afghanistan · 1889", "Herat, Afghanistan", "Afghanistan", 34.353, 62.204,
      "An illustrated ketubah from the Jewish community of Herat, Afghanistan, 1889."),
    ket(14, "040", "10428", 1894, "London, England · 1894", "London, England", "England", 51.507, -0.128,
      "An illustrated ketubah from London, 1894, formerly in the Sassoon Library.", null, true),

    {
      id: 15,
      title: "Haym Salomon's account of financing the synagogue",
      creator: "Haym Salomon (1740–1785)",
      year: 1784, dateText: "Philadelphia · ca. 1784", place: "Philadelphia, USA",
      region: "United States", lat: 39.9496, lng: -75.1503,
      lang: "English", type: "Manuscript", collection: "Congregation Mikveh Israel Records",
      source: "mikveh", iiif: true,
      img: haymPages[0].img, srcUrl: OP + "/Data/0039/html/MikvehIsrael.HaymSalomonManuscript.html", callno: "Mikveh Israel",
      desc: "A scribal copy of Haym Salomon's own account of purchasing the property and financing the construction of Mikveh Israel's synagogue in 1782 — including his pledge of one-fourth the cost, 'be it what it might.' Salomon was a central financier of the American Revolution.",
      pages: haymPages
    },
    {
      id: 16,
      title: "Jonas Phillips letter on the new synagogue",
      creator: "Jonas Phillips (1736–1803)",
      year: 1782, dateText: "Philadelphia · 1782", place: "Philadelphia, USA",
      region: "United States", lat: 39.9489, lng: -75.1490,
      lang: "English", type: "Letter", collection: "Congregation Mikveh Israel Records",
      source: "mikveh", iiif: true,
      img: jonasPages[0].img, srcUrl: OP + "/Data/0039/html/MikvehIsrael.JonasPhillipsLetter1782.html", callno: "Mikveh Israel",
      desc: "A 1782 letter from merchant and Revolutionary War veteran Jonas Phillips — then president of Mikveh Israel — objecting to the proposed plan for the congregation's new synagogue on grounds of space, proximity to neighbors, and the placement of the door.",
      pages: jonasPages
    }
  ];

  window.PJP = { sources: sources, items: items, featured: [1, 2, 15, 9], harvestedAt: "2026-05 (beta sample)" };
})();
